In [1]:
from google_play_scraper import reviews, Sort
import pandas as pd
import numpy as np
import time

import re
import string
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.corpus import stopwords

In [2]:
result, continuation_token = reviews(
    'com.mobile.legends',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=10000,
    filter_score_with=None
)

In [3]:
df = pd.DataFrame(np.array(result),columns=['review'])

df = df.join(pd.DataFrame(df.pop('review').tolist()))

df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,64da7393-7c68-4f4c-a60a-cb83d6f755ea,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Terungkap Developer..... Saya mungkin hanya sa...,2,8,2.1.61.11705,2026-03-29 04:49:46,"Halo Kak,\nKami berkomitmen untuk menciptakan ...",2026-03-29 10:06:41,2.1.61.11705
1,55e6b801-9683-4126-9de1-7684539d9c23,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Ketika Saya bertanding, sesuatu terjadi. Analo...",2,2,2.1.61.11705,2026-04-08 22:46:01,None,NaT,2.1.61.11705
2,e1c85852-26e5-453e-9224-9db6a94a419a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"game paling sampah setelah ff, gw sbgai player...",1,2,2.1.61.11705,2026-04-12 12:05:52,None,NaT,2.1.61.11705
3,32903c9a-cd0a-42b2-ae40-f69bb1874c17,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sejujurnya main nih game ga harus yang gimana-...,3,1,2.1.61.11705,2026-04-12 20:22:49,None,NaT,2.1.61.11705
4,82ecb38c-e9e5-4327-b2da-4fe3a19b82fd,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Makin di Update makin buruk, terutama di jarin...",1,9,2.1.61.11705,2026-03-25 19:04:40,None,NaT,2.1.61.11705
...,...,...,...,...,...,...,...,...,...,...,...
9995,509d6241-1f1f-4e10-90c3-eaa2fd7ee378,Evander Agustons,https://play-lh.googleusercontent.com/a/ACg8oc...,ngasih tim yang bener dikitlah masa satu tim i...,1,17,2.1.47.11491,2026-02-06 20:56:46,None,NaT,2.1.47.11491
9996,0cad9b38-f6cc-4361-8ceb-dd250caec1fe,Yovan nata (Yovan),https://play-lh.googleusercontent.com/a-/ALV-U...,"Benerin dulu tuh server lag nya, bener-bener b...",1,0,2.1.61.11705,2026-03-18 10:11:08,None,NaT,2.1.61.11705
9997,d0f8e6c4-3ef7-4a5e-ae18-382abc211dd1,Nasrul,https://play-lh.googleusercontent.com/a/ACg8oc...,"game yg isi nya dark sistem, masa matchmaking ...",1,1,2.1.47.11491,2026-02-08 11:21:23,None,NaT,2.1.47.11491
9998,c7ef224e-2f7e-4b9a-940b-c6f8fcd72888,wahyu ghadafi,https://play-lh.googleusercontent.com/a-/ALV-U...,walaupun banyak dark sistem di saat main rank ...,5,0,2.1.41.11465,2026-02-24 03:57:38,None,NaT,2.1.41.11465
9999,0ef564cd-1090-4ca8-b871-06e370884eec,Zaniii Zanii,https://play-lh.googleusercontent.com/a/ACg8oc...,"game tolol,banyak bocil yang main. monton Tida...",1,4,2.1.31.11233,2025-12-18 15:47:51,None,NaT,2.1.31.11233

In [4]:
len(df.index)

10000

In [5]:
df[['userName', 'score','at', 'content']]

,userName,score,at,content
0,Pengguna Google,2,2026-03-29 04:49:46,Terungkap Developer..... Saya mungkin hanya sa...
1,Pengguna Google,2,2026-04-08 22:46:01,"Ketika Saya bertanding, sesuatu terjadi. Analo..."
2,Pengguna Google,1,2026-04-12 12:05:52,"game paling sampah setelah ff, gw sbgai player..."
3,Pengguna Google,3,2026-04-12 20:22:49,sejujurnya main nih game ga harus yang gimana-...
4,Pengguna Google,1,2026-03-25 19:04:40,"Makin di Update makin buruk, terutama di jarin..."
...,...,...,...,...
9995,Evander Agustons,1,2026-02-06 20:56:46,ngasih tim yang bener dikitlah masa satu tim i...
9996,Yovan nata (Yovan),1,2026-03-18 10:11:08,"Benerin dulu tuh server lag nya, bener-bener b..."
9997,Nasrul,1,2026-02-08 11:21:23,"game yg isi nya dark sistem, masa matchmaking ..."
9998,wahyu ghadafi,5,2026-02-24 03:57:38,walaupun banyak dark sistem di saat main rank ...
9999,Zaniii Zanii,1,2025-12-18 15:47:51,"game tolol,banyak bocil yang main. monton Tida..."

In [6]:
df = df[['userName', 'score','at', 'content']]
df = df.sort_values(by='at', ascending=False)
df

,userName,score,at,content
5311,Pengguna Google,5,2026-04-14 10:39:35,"skin itachi keren banget, tapi mohon lebih di ..."
9380,Ayesha Kinara,2,2026-04-14 09:58:56,tolong buat moonton aku main terus renk nya ga...
6063,Pengguna Google,1,2026-04-14 09:28:32,game sampah player nya juga banyak sampahnya s...
1919,Pengguna Google,1,2026-04-14 09:06:01,"kalo ngasih tim kira kira dikit lah, ga sesuai..."
9935,Naufal Firdaus,1,2026-04-14 08:59:30,gw dari pagi sampai sori gak pernah dapet mage...
...,...,...,...,...
7562,Pengguna Google,1,2025-11-06 21:52:56,Ketidakadilan Rank: Seringkali pemain merasa d...
9472,Kaaa Sa,3,2025-11-06 16:06:17,"game kompetitif, yang cukup menarik dengan per..."
7585,Pengguna Google,1,2025-11-06 15:48:38,game ini sudah sangat bagus tetapi ada beberap...
8137,Pengguna Google,1,2025-11-05 16:52:29,"Game toxic,penuh cacian makian,game aneh bug d..."
6150,Pengguna Google,2,2025-11-05 15:27:32,"game bagus, namun saya memiliki saran yaitu fi..."

In [7]:
df = df[["score", "content"]]
df

      score                                            content
5311      5  skin itachi keren banget, tapi mohon lebih di ...
9380      2  tolong buat moonton aku main terus renk nya ga...
6063      1  game sampah player nya juga banyak sampahnya s...
1919      1  kalo ngasih tim kira kira dikit lah, ga sesuai...
9935      1  gw dari pagi sampai sori gak pernah dapet mage...
...     ...                                                ...
7562      1  Ketidakadilan Rank: Seringkali pemain merasa d...
9472      3  game kompetitif, yang cukup menarik dengan per...
7585      1  game ini sudah sangat bagus tetapi ada beberap...
8137      1  Game toxic,penuh cacian makian,game aneh bug d...
6150      2  game bagus, namun saya memiliki saran yaitu fi...

[10000 rows x 2 columns]

In [8]:
def label(score):
    if score <= 4:
        return 'negative'
    else:
        return 'positive'
    
df['sentiment'] = df['score'].apply(label)
df

C:\Users\acer\AppData\Local\Temp\ipykernel_3484\1087463446.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment'] = df['score'].apply(label)

      score                                            content sentiment
5311      5  skin itachi keren banget, tapi mohon lebih di ...  positive
9380      2  tolong buat moonton aku main terus renk nya ga...  negative
6063      1  game sampah player nya juga banyak sampahnya s...  negative
1919      1  kalo ngasih tim kira kira dikit lah, ga sesuai...  negative
9935      1  gw dari pagi sampai sori gak pernah dapet mage...  negative
...     ...                                                ...       ...
7562      1  Ketidakadilan Rank: Seringkali pemain merasa d...  negative
9472      3  game kompetitif, yang cukup menarik dengan per...  negative
7585      1  game ini sudah sangat bagus tetapi ada beberap...  negative
8137      1  Game toxic,penuh cacian makian,game aneh bug d...  negative
6150      2  game bagus, namun saya memiliki saran yaitu fi...  negative

[10000 rows x 3 columns]

In [ ]:
# Fungsi pra-pemrosesan
factory = StemmerFactory()
stemmer = factory.create_stemmer()
stop_words = set(stopwords.words('indonesian'))

def clean_text(text):
    # Lowercase
    text = text.lower()
    # Hapus angka
    text = re.sub(r'\d+', '', text)
    # Hapus tanda baca
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Hapus whitespace berlebih
    text = text.strip()
    # Tokenisasi manual
    tokens = text.split()
    # Hapus stopwords
    tokens = [word for word in tokens if word not in stop_words]
    # Stemming
    tokens = [stemmer.stem(word) for word in tokens]
    return ' '.join(tokens)

# Terapkan ke kolom content (ganti 'content' sesuai nama kolom di df)
df['clean_review'] = df['content'].apply(clean_text)
df[['content', 'clean_review']].head()
df